name: Semantic Versioning POC

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
     contents: write
     pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install GitVersion Tool
        run: dotnet tool install --global GitVersion.Tool --version 5.*

      - name: Add .NET Tools Path
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: Run GitVersion
        id: gitversion
        run: dotnet-gitversion . /output json /output buildserver

      - name: Debug GitVersion Output
        run: |
          echo "GitVersion Output (semVer): ${{ steps.gitversion.outputs.semVer }}"


      - name: Output GitVersion
        run: |
          echo "Version: ${{ steps.gitversion.outputs.semVer }}"

      - name: Tag Release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v2.1.0${{ steps.gitversion.outputs.semVer }}" -m "Release v${{ steps.gitversion.outputs.semVer }}"
          git push origin "v2.1.0${{ steps.gitversion.outputs.semVer }}"


      - name: Create Output Directory
        run: mkdir -p build/output

      - name: Create a dummy file to be artifact
        run: |
         echo "This is a dummy build artifact file. Version: ${{ steps.gitversion.outputs.semVer }}" > build/output/artifact.txt
         ls -l build/output
      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: app-${{ steps.gitversion.outputs.semVer }}
            path: build/output
